name: Release Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Version Up
        run: |
          npm version ${{ github.event.release.tag_name }}
          git push
      - uses: ./.github/actions/build
      - name: Publish
        run: npm publish --access public
