name: Release Package

on:
  workflow_dispatch:
    inputs:
      release-version:
        type: string
        required: true
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Publish
        run: npm publish --access public 