name: Release Package

on:
  workflow_dispatch:
    inputs:
      release-version:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
