name: Update Version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      auto-merge:
        type: boolean
        default: false
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      auto-merge:
        type: boolean
        default: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Version Up
        id: version-up
        continue-on-error: true
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          npm version "${{ inputs.version }}"
      - uses: peter-evans/create-pull-request@v5
        id: create-pr
        if: steps.version-up.outcome == 'success'
        with:
          commit-message: 'update version: ${{ inputs.version }}'
          delete-branch: true
          title: 'update version: ${{ inputs.version }}'
          branch-suffix: timestamp
          base: ${{ github.ref_name }}
      - uses: peter-evans/enable-pull-request-automerge@v3
        if: inputs.auto-merge && steps.create-pr.outputs.pull-request-number
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}