name: Test

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Version Up
        run: npm version "${{ inputs.version }}"
      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'update version: ${{ inputs.version }}'
          delete-branch: true
          title: 'update version: ${{ inputs.version }}'
