name: Update Version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Version Up
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          npm version "${{ inputs.version }}"
      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'update version: ${{ inputs.version }}'
          delete-branch: true
          title: 'update version: ${{ inputs.version }}'
          branch-suffix: ${{ github.run_id }}
